export const USER_REGISTERED = 'USER_REGISTERED';

export const USER_VERIFIED = 'USER_VERIFIED';

export const USER_REGISTRATION_ERROR = 'USER_REGISTRATION_ERROR';

export const USER_LOGGED_IN = 'USER_LOGGED_IN';

export const USER_FETCHED = 'USER_FETCHED';

export const VERSION_FETCHED = 'VERSION_FETCHED'

export const PROFILE_UPDATED = 'PROFILE_UPDATED';

export const USER_FETCHED_BY_PHONE = 'USER_FETCHED_BY_PHONE';

export const USER_PASSWORD_RESET = 'USER_PASSWORD_RESET';

export const RESET_CODE_VERIFIED = 'RESET_CODE_VERIFIED';

export const CONTACTS_FETCHED = 'CONTACTS_FETCHED';

export const USER_FETCHED_BY_EMAIL = 'USER_FETCHED_BY_EMAIL';

export const CONTACTS_INVITED = 'CONTACTS_INVITED';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const RESET_CODE_SENT = 'RESET_CODE_SENT';

export const CIRCLE_CREATED = 'CIRCLE_CREATED';

export const CIRCLES_FETCHED = 'CIRCLES_FETCHED';

export const CIRCLE_DATA_FETCHED = 'CIRCLE_DATA_FETCHED';

export const CIRCLE_MEMBERS_FETCHED = 'CIRCLE_MEMBERS_FETCHED';

export const NOTIFICATION_FETCHED = 'NOTIFICATION_FETCHED';

export const NOTIFICATION_SPECIFIED = 'NOTIFICATION_SPECIFIED';

export const RESET_ACTION_CIRCLE_CREATED = 'RESET_ACTION_CIRCLE_CREATED';

export const RESET_ACTION_CONTACT_INVITED = 'RESET_ACTION_CONTACT_INVITED';

export const RESET_ACTION_PASSWORD_RESET = 'RESET_ACTION_PASSWORD_RESET';

export const RESET_USEREGISTERED = 'RESET_USEREGISTERED';


export const CLEAR_CIRCLE_DATA = 'CLEAR_CIRCLE_DATA';

export const CLEAR_CIRCLE_MEMBER = 'CLEAR_CIRCLE_MEMBER';

export const CIRCLE_UPDATED = 'CIRCLE_UPDATED';

export const CIRCLE_MEMBERS_ADDED = 'CIRCLE_MEMBERS_ADDED';

export const RESET_CIRCLE_MEMBER_ADDED = 'RESET_CIRCLE_MEMBER_ADDED';

export const NOTIFICATION_REMOVED = 'NOTIFICATION_REMOVED';

export const ERROR_SIGN_UP = 'ERROR_SIGN_IN';

export const RESET_ERROR_SIGN_UP = 'RESET_ERROR_SIGN_IN';

export const LOADING_SIGN_UP = 'LOADING_SIGN_IN';

export const LOADING_PROFILE = 'LOADING_PROFILE';

export const LOADING_CONTACTS = 'LOADING_CONTACTS';

export const ERROR_PROFILE = 'ERROR_PROFILE';

export const RESET_ERROR_PROFILE = 'RESET_ERROR_PROFILE';

export const ERROR_CONTACTS = 'ERROR_CONTACTS';

export const RESET_ERROR_CONTACTS = 'RESET_ERROR_CONTACTS';

export const PHONE_UPDATE_CODE_SENT = 'PHONE_UPDATE_CODE_SENT';

export const RESET_PHONE_UPDATE_CODE = 'RESET_PHONE_UPDATE_CODE';

export const PHONE_UPDATED = "PHONE_UPDATED";

export const RESET_PHONE_UPDATED = "RESET_PHONE_UPDATED";

export const LOADING_JOURNEY = "LOADING_JOURNEY";

export const ERROR_JOURNEY = "ERROR_JOURNEY";

export const RESET_ERROR_JOURNEY = "RESET_ERROR_JOURNEY";

export const SELECT_CIRCLE = "SELECT_CIRCLE";

export const SELECT_IMAGE = "SELECT_IMAGE";

export const SELECT_MESSAGE = "SELECT_MESSAGE";

export const SELECT_DATE_AND_OCCASSION = "SELECT_DATE_AND_OCCASSION";

export const RESET_JOURNEY_MESSAGE = "RESET_JOURNEY_MESSAGE";

export const RESET_JOURNEY_MESSAGE_Date = "RESET_JOURNEY_MESSAGE_Date";


export const RESET_FLORIST = "RESET_FLORIST";




export const JOURNEY_CREATED = "JOURNEY_CREATED";

export const ERROR_CIRCLE = "ERROR_CIRCLE";

export const LOADING_CIRCLE = "LOADING_CIRCLE";

export const RESET_ERROR_CIRCLE = "RESET_ERROR_CIRCLE";

export const SELECT_ENVELOPE_TYPE = "SELECT_ENVELOPE_TYPE";

export const JOURNEY_FETCHED = "JOURNEY_FETCHED";

export const DRAFTS_FETCHED = "DRAFTS_FETCHED";

export const SCHEDULED_FETCHED = "SCHEDULED_FETCHED";

export const JOURNEY_OPENED = "JOURNEY_OPENED";

export const LOADING_NOTIFICATION = "LOADING_NOTIFICATION";

export const RESET_JOURNEY_CREATED = "RESET_JOURNEY_CREATED";

export const DELIVERED_FETCHED = "DELIVERED_FETCHED";

export const SELECT_VIDEO = "SELECT_VIDEO";

export const AUDIO_URL = "AUDIO_URL";

export const DELETE_PROFILE_IMAGE = "DELETE_PROFILE_IMAGE";

export const JOURNEY_COMMENTED = "JOURNEY_COMMENTED";

export const RESET_JOURNEY_COMMENT = "RESET_JOURNEY_COMMENT";

export const COMMENTS_FETCHED = "COMMENTS_FETCHED";

export const LIKES_FETCHED = "LIKES_FETCHED";

export const RESET_CURRENT_JOURNEY = "RESET_CURRENT_JOURNEY";

export const SINGLE_JOURNEY_FETCHED = "SINGLE_JOURNEY_FETCHED";

export const RESET_SINGLE_JOURNEY = "RESET_SINGLE_JOURNEY";

export const NOTIFICATION_UPDATED = "NOTIFICATION_UPDATED";

export const JOURNEY_FILTERED = "JOURNEY_FILTERED"

export const RECEIVED_CHECKED = "RECEIVED_CHECKED"

export const DELIVERED_CHECKED = "DELIVERED_CHECKED"

export const SCHEDULED_CHECKED = "SCHEDULED_CHECKED"

export const ALL_CHECKED = "All_CHECKED"

export const SET_SELECTED_CIRCLE = "SET_SELECTED_CIRCLE"

export const SET_SELECTED_CONTACT = "SET_SELECTED_CONTACT"

export const SELECT_TOKEN = "SELECT_TOKEN"

export const RESET_TOKEN = "RESET_TOKEN"

export const FCM_TOKEN = "FCM_TOKEN"

export const SELECT_GIFT_MESSAGE = "SELECT_GIFT_MESSAGE"

export const RECEIVER_FETCHED = "RECEIVER_FETCHED"

export const SET_RECEIVER_ID = "SET_RECEIVER_ID"

export const SET_CARD_NO = "SET_CARD_NO"

export const SET_CARD_EXPIRY = "SET_CARD_EXPIRY"

export const SET_CARD_CVC = "SET_CARD_CVC"

export const SET_FLOWER = "SET_FLOWER"

export const CHECK_FLOURIST_AVAILABLITY = "CHECK_FLOURIST_AVAILABLITY"

export const FLOURIST_TOKEN_FETCHED = "FLOURIST_TOKEN_FETCHED"

export const SET_ORDER_TOTAL = "SET_ORDER_TOTAL"

export const GALLERY_FETCHED = "GALLERY_FETCHED"

export const SET_CARD_EXPIRY_MONTH = "SET_CARD_EXPIRY_MONTH"

export const ORDER_TOTAL_FETCHED = "ORDER_TOTAL_FETCHED"

export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR"

export const CLOSE_CONTACT = "CLOSE_CONTACT"

export const COMET_CHAT_USERS_FETCHED = "COMET_CHAT_USERS_FETCHED"

export const COMET_CHAT_GROUPS_FETCHED = "COMET_CHAT_GROUPS_FETCHED"

export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"

export const IS_DRAFT = "IS_DRAFT"

export const SET_COMET_CHAT_USER = "SET_COMET_CHAT_USER"

export const SET_COMET_CHAT_USER_GROUP = "SET_COMET_CHAT_USER_GROUP"


export const OPEN_JOURNEY_FETCHED = "OPEN_JOURNEY_FETCHED"
export const OPEN_JOURNEY_LOADING = "OPEN_JOURNEY_LOADING"
export const OPEN_JOURNEY_REFRESHING = "OPEN_JOURNEY_REFRESHING"

export const INCOMING_JOURNEY_FETCHED = "INCOMING_JOURNEY_FETCHED"
export const INCOMING_JOURNEY_FILTERED = "INCOMING_JOURNEY_FILTERED"
export const INCOMING_JOURNEY_FETCHED_MORE = "INCOMING_JOURNEY_FETCHED_MORE"
export const INCOMING_REFRESH = "INCOMING_REFRESH"

export const OUTGOING_JOURNEY_FETCHED = "OUTGOING_JOURNEY_FETCHED"

export const SELECT_PROFILE_IMAGE = "SELECT_PROFILE_IMAGE"

export const PHONE_VERIFIED = "PHONE_VERIFIED"

export const USER_UPDATED = "USER_UPDATED"

export const SELECT_SIGNUP_CONTACT = "SELECT_SIGNUP_CONTACT"

export const RESET_USER_UPDATE = "RESET_USER_UPDATE"

export const FETCHED_INVITED_CONTACTS = "FETCHED_INVITED_CONTACTS"

export const FETCHED_RECENT_CIRCLES = "FETCHED_RECENT_CIRCLES"

export const FETCHED_RECENT_CONTACTS = "FETCHED_RECENT_CONTACTS"

export const SET_RECEIVER_TIME = "SET_RECEIVER_TIME"

export const SET_CONVERSATIONS = "SET_CONVERSATIONS"

export const SET_SHOW_MORE = "SET_SHOW_MORE"

export const FETCH_CARDS = "FETCH_CARDS"
export const FETCH_ALL_CARDS = "FETCH_ALL_CARDS"
export const FETCH_CARDS_ERROR = "FETCH_CARDS_ERROR"
export const FETCH_SPECIFIC_CARDS = "FETCH_SPECIFIC_CARDS"

export const LOADING_CHAT = 'LOADING_CHAT';

export const FETCH_SCHEDULED_MESSAGES_BY_ID = 'FETCH_SCHEDULED_MESSAGES_BY_ID';